### ISSUE TITLE
support more async methods

### ISSUE THREAD

**Issue by jhgbrt** [jhgbrt/yadal#6]

**Comment by jhgbrt** [comment]
This requires working with the ADO.Net abstract classes instead of the interfaces (change that was overdue anyway)

**Comment by kpp-mantleanalytics** [comment]
Hi @jhgbrt ,

You have done really a good job. May I know if it supports async calls? 

Regards,
KP

**Comment by jhgbrt** [comment]
Hello, yes, in the mean time it does. See https://github.com/jhgbrt/yadal/blob/master/Net.Code.ADONet/AsyncExecutor.cs for the implementation, and the unit tests (https://github.com/jhgbrt/yadal/blob/master/Net.Code.ADONet.Tests.Unit/CommandExecutionTests.cs) for how to work with the async methods
