### ISSUE TITLE
Getting an exception with parameters

### ISSUE THREAD

**Issue by kpp-mantleanalytics** [jhgbrt/yadal#7]
Hi @jhgbrt ,

Could please help on below issue? Getting a exception = {"Invalid object name '@schema.@tablename'."}

```
using (var db = new Db(connectionString, SqlClientFactory.Instance))
{
var query = db.Sql("SELECT * FROM [@schema].[@tablename]").WithParameters(new { schema = "dbo", tablename = "student" });
 var list = query.AsEnumerable().Select(row => row).ToList();
}
```

I have several schemas and table to which I need to connect. 

Regards,
KP

**Comment by kpp-mantleanalytics** [comment]
Hi @jhgbrt,

My bad we cant call tablename as parameter, however after correction I am not getting any result out of AsEnumerableAsync(), however getting result if I call AsDataTable() method as below

```
using (SqlCommand cmd = new SqlCommand())
            {
                cmd.Connection = new SqlConnection(connectionString);
                CommandBuilder cb = new CommandBuilder(cmd, DbConfig.Default);
                cb.Command.CommandType = System.Data.CommandType.StoredProcedure;
                cb.WithCommandText("sp_executesql");
                cb.WithParameter("@sqlQuery", "SELECT * FROM [dbo].[student]");

                var str = JsonConvert.SerializeObject(await cb.AsEnumerableAsync()); // Not getting any data
                //var str = JsonConvert.SerializeObject(cb.AsDataTable()); // Getting data
            }
```

**Comment by jhgbrt** [comment]
What do you get when you enumerate the result explicitly?

    var enumerable = await cb.AsEnumerableAsync();
    var list = await enumerable.ToListAsync(); // requires System.Linq.Async 
    var str = JsonConvert.SerializeObject(list);

Is this SQL server?

**Comment by jhgbrt** [comment]
You should be able to do something like this:

```
using  (var db = new Db(connectionString, SqlClientFactory.Instance))
{
    await _db.Sql("SELECT * FROM [dbo].[student]")
                        .AsEnumerableAsync()
                        .Select(d => new Student {Id = d.Id, Name = d.Name}) // project from dynamic to Student object
                        .ToListAsync();
}

**Comment by kpp-mantleanalytics** [comment]
Hi @jhgbrt ,

Thanks for replying. yes its SQL server but I don't have POCOs/entity class Actually I would be connecting to many databases & tables so cant create these many POCOs/entity classes. So planning to serialize dynamic objects to JSON. 

Regards,
Kiran

**Comment by jhgbrt** [comment]
What happens if you leave out the Select?

**Comment by kpp-mantleanalytics** [comment]
Hi @jhgbrt ,

I installed System.Linq.Async however still getting error at .ToListAsync(). I am using console application to test this and .net framework 4.8. 

`var enumerable = await cb.AsEnumerableAsync();
var list = await enumerable.ToListAsync(); // requires System.Linq.Async 
var str = JsonConvert.SerializeObject(list);`

**Comment by jhgbrt** [comment]
What error?

**Comment by kpp-mantleanalytics** [comment]
Error : IEnumerable<dynamic> does not contain a definition for ToListAsync

```
using Net.Code.ADONet;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Linq.Async;

namespace FluentAdonet
{
    class Program
    {
        static async Task Main(string[] args)
        {
            string connectionString = $@"xxx";
            using (SqlCommand cmd = new SqlCommand())
            {
                cmd.Connection = new SqlConnection(connectionString);
                CommandBuilder cb = new CommandBuilder(cmd, DbConfig.Default);
                cb.Command.CommandType = System.Data.CommandType.StoredProcedure;
                cb.WithCommandText("sp_executesql");
                cb.WithParameter("@sqlQuery", "SELECT * FROM [dbo].[student]");

                var enumerable = await cb.AsEnumerableAsync();
                var list = await enumerable.ToListAsync(); // requires System.Linq.Async 
                var str = JsonConvert.SerializeObject(list);
            }

        }


    }
}
```

**Comment by kpp-mantleanalytics** [comment]
Type or namespace name 'Async' does not exist in namespace System.Linq

**Comment by jhgbrt** [comment]
The code below works for me (using SqLite, but that should not make a difference). Did you add a reference to the System.Linq.Async package? Note the using statement is just "using System.Linq".

Unfortunately it seems that indeed the dynamic object returned from AsEnumerableAsync (or AsEnumerable for that matter) can not be directly serialized to Json. Could you please log a separate issue for that? I can't promise a fix date however.


```
using Microsoft.Data.Sqlite;
using Net.Code.ADONet;
using Newtonsoft.Json;
using System;
using System.Linq;

using var db = new Db("Data Source=:memory:", SqliteFactory.Instance);

await db.Sql("CREATE TABLE Student (Id int, Name nvarchar(100))").AsNonQueryAsync();
await db.Sql("INSERT INTO Student (Id, Name) VALUES (@Id, @Name)").WithParameters(new { Id = 1, Name = "John Doe"}).AsNonQueryAsync();

var list = await db.Sql("SELECT * FROM Student")
    .AsEnumerableAsync()
    .Select(d => new {Id = d.Id, Name = d.Name})
    .ToListAsync();
Console.WriteLine(JsonConvert.SerializeObject(list));

**Comment by jhgbrt** [comment]
closing this issue, please log a new one for the serialization issue

**Comment by jhgbrt** [comment]
I think I've already fixed it. Could you try with version 5.0.0 preview 4? On my machine, this works now:

```
using var db = new Db("Data Source=:memory:", SqliteFactory.Instance);

await db.Sql("CREATE TABLE Student (Id int, Name nvarchar(100))").AsNonQueryAsync();
await db.Sql("INSERT INTO Student (Id, Name) VALUES (@Id, @Name)").WithParameters(new { Id = 1, Name = "John Doe"}).AsNonQueryAsync();

var list = await db.Sql("SELECT * FROM Student")
    .AsEnumerableAsync()
    .ToListAsync();

**Comment by kpp-mantleanalytics** [comment]
Do you mean System.Linq.Async 5.0.0 preview 4 ? Where can I find it?

**Comment by kpp-mantleanalytics** [comment]
yes got it. Yes its working fine. :)

**Comment by kpp-mantleanalytics** [comment]
I really appreciate your help. Thank you so much.
